<?xml version="1.0"?>
<robot name="restorebot" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:property name="AlDensity" value="2712" />

	<xacro:property name="platLen" value="8" />
	<xacro:property name="platWidth" value="8" />
	<xacro:property name="platHeight" value="1" />

	<xacro:property name="satLen" value="${5}" />
	<xacro:property name="satWidth" value="${5}" />
	<xacro:property name="satHeight" value="${5}" />

	<xacro:property name="cylRad" value="0.2" />
	<xacro:property name="cylLen" value = "0.8" />

	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>

	<material name="black">
		<color rgba="0 .2 0 1"/>
	</material>

	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>

	<material name="cyan">
		<color rgba="0 1 1 1"/>
	</material>



	<!--	****************
			****************
			****************

			Base Platform

			****************
			****************
			****************
	-->

	<link name="platform_base">

		<xacro:property name="box_mass" value="${AlDensity*platLen*platWidth*platHeight}" />
		<xacro:macro name="default_box_inertia" params="mass">
			<inertial>
				<mass value="${mass}" />
				<inertia ixx="${platHeight*platHeight/12+platWidth*platWidth/12}" ixy="0.0" ixz="0.0" iyy="${platHeight*platHeight/12+platLen*platLen/12}" iyz="0.0" izz="${platLen*platLen/12 +platWidth*platWidth/12}" />
			</inertial>
		</xacro:macro>

		<xacro:macro name="platform_geom">
			<geometry>
				<box size="${platLen} ${platWidth} ${platHeight}" />
			</geometry>
		</xacro:macro>

		<visual>
			<xacro:platform_geom />
			<material name = "black"/>
		</visual>
		<collision>
			<xacro:platform_geom />
		</collision>
		<xacro:default_box_inertia mass ="${box_mass}" />
	</link>

	<!--	****************
			****************
			****************

 				Arm Link 1

			****************
			****************
			****************
	-->

	<link name="armLink1">

		<xacro:macro name="armLink1_geom">
			<geometry>
				<cylinder length="${armLink1Len}" radius="${armLink1Rad}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink1_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink1Len/2}" />
		</xacro:macro>

		<xacro:property name="armLink1Rad" value="${cylRad}" />
		<xacro:property name="armLink1Len" value = "${cylLen/2}" />
		<xacro:property name="armLink1Mass" value = 
				"${AlDensity*3.14*armLink1Len*armLink1Rad*armLink1Rad}" />
		<visual>
			<xacro:armLink1_geom />
			<xacro:armLink1_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink1_geom />
			<xacro:armLink1_offset />
		</collision>
		<inertial>
			<mass value="${armLink1Mass}" />
			<inertia ixx="${armLink1Len*armLink1Len/3+armLink1Rad*armLink1Rad/4}" ixy="0.0" ixz="0.0" iyy="${armLink1Len*armLink1Len/3+armLink1Rad*armLink1Rad/4}" iyz="0.0" izz="${armLink1Rad*armLink1Rad/2}" />
		</inertial>
	</link>

	<joint name="base_to_link1" type ="continuous">
		<parent link="platform_base"/>
		<child link="armLink1"/>
		<origin rpy = "0 0 0" xyz="${platLen/4} ${platWidth/4} ${platHeight/2}" />
		<axis xyz = "0 0 1" />
	</joint>

	<link name="armLink1square">
		
		<xacro:property name="armLink1squareLen" value="${armLink1Rad*2.2}" />
		<xacro:property name="armLink1squareMass" value="${AlDensity*armLink1squareLen*armLink1squareLen*armLink1squareLen}" />
		
		<xacro:macro name="armLink1square_geom">
			<geometry>
				<box size="${armLink1squareLen} ${armLink1squareLen} ${armLink1squareLen}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink1square_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink1squareLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:armLink1square_geom />
			<xacro:armLink1square_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink1square_geom />
			<xacro:armLink1square_offset />
		</collision>
		<inertial>
			<mass value="${armLink1squareMass}" />
			<inertia ixx="${armLink1squareLen*armLink1squareLen * 5/12}" ixy="0.0" ixz="0.0" iyy="${armLink1squareLen*armLink1squareLen * 5/12}" iyz="0.0" izz="${armLink1squareLen*armLink1squareLen / 6}" />
		</inertial>
	</link>	
s
	<joint name="armLink1Fixed" type ="fixed">
		<parent link="armLink1"/>
		<child link="armLink1square"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink1Len}" />
	</joint>

	<!--	****************
			****************
			****************

 				Arm Link 2

			****************
			****************
			****************
	-->

	<link name="armLink2">
		
		<xacro:property name="armLink2Len" value="${armLink1squareLen}" />
		<xacro:property name="armLink2Mass" value="${AlDensity*armLink2Len*armLink2Len*armLink2Len}" />
		
		<xacro:macro name="armLink2_geom">
			<geometry>
				<box size="${armLink2Len} ${armLink2Len} ${armLink2Len}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink2_offset">
			<origin rpy = "0 0 0" xyz="0 0 0" />
		</xacro:macro>

		<visual>
			<xacro:armLink2_geom />
			<xacro:armLink2_offset />
			<material name="blue"/>
		</visual>
		<collision>
			<xacro:armLink2_geom />
			<xacro:armLink2_offset />
		</collision>
		<inertial>
			<mass value="${armLink2Mass}" />
			<inertia ixx="${armLink2Len*armLink2Len /6}" ixy="0.0" ixz="0.0" iyy="${armLink2Len*armLink2Len/6}" iyz="0.0" izz="${armLink2Len*armLink2Len /6}" />
		</inertial>
	</link>	
	
	<joint name="armLink1_to_armLink2" type ="continuous">
		<parent link="armLink1square"/>
		<child link="armLink2"/>
		<origin rpy = "0 0 0" xyz="${armLink1squareLen} 0 ${armLink2Len/2}" />
		<axis xyz = "1 0 0" />
	</joint>

	<!--	****************
			****************
			****************

 				Arm Link 3

			****************
			****************
			****************
	-->

	<link name="armLink3">

		<xacro:macro name="armLink3_geom">
			<geometry>
				<cylinder length="${armLink3Len}" radius="${armLink3Rad}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink3_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink3Len/2}" />
		</xacro:macro>

		<xacro:property name="armLink3Rad" value="${cylRad}" />
		<xacro:property name="armLink3Len" value = "${cylLen}" />
		<xacro:property name="armLink3Mass" value = 
				"${AlDensity*3.14*armLink3Len*armLink3Rad*armLink3Rad}" />
		<visual>
			<xacro:armLink3_geom />
			<xacro:armLink3_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink3_geom />
			<xacro:armLink3_offset />
		</collision>
		<inertial>
			<mass value="${armLink3Mass}" />
			<inertia ixx="${armLink3Len*armLink3Len/3+armLink3Rad*armLink3Rad/4}" ixy="0.0" ixz="0.0" iyy="${armLink3Len*armLink3Len/3+armLink3Rad*armLink3Rad/4}" iyz="0.0" izz="${armLink3Rad*armLink3Rad/2}" />
		</inertial>
	</link>

	<joint name="armLink2_to_armLink3" type ="continuous">
		<parent link="armLink2"/>
		<child link="armLink3"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink2Len/2}" />
		<axis xyz = "0 0 1" />
	</joint>

	<link name="armLink3square">
		
		<xacro:property name="armLink3squareLen" value="${armLink3Rad*2.2}" />
		<xacro:property name="armLink3squareMass" value="${AlDensity*armLink3squareLen*armLink3squareLen*armLink3squareLen}" />
		
		<xacro:macro name="armLink3square_geom">
			<geometry>
				<box size="${armLink3squareLen} ${armLink3squareLen} ${armLink3squareLen}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink3square_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink3squareLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:armLink3square_geom />
			<xacro:armLink3square_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink3square_geom />
			<xacro:armLink3square_offset />
		</collision>
		<inertial>
			<mass value="${armLink3squareMass}" />
			<inertia ixx="${armLink3squareLen*armLink3squareLen * 5/12}" ixy="0.0" ixz="0.0" iyy="${armLink3squareLen*armLink3squareLen * 5/12}" iyz="0.0" izz="${armLink3squareLen*armLink3squareLen / 6}" />
		</inertial>
	</link>	

	<joint name="armLink3Fixed" type ="fixed">
		<parent link="armLink3"/>
		<child link="armLink3square"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink3Len}" />
	</joint>

	<!--	****************
			****************
			****************

 				Arm Link 4

			****************
			****************
			****************
	-->

	<link name="armLink4">
		
		<xacro:property name="armLink4Len" value="${armLink3squareLen}" />
		<xacro:property name="armLink4Mass" value="${AlDensity*armLink4Len*armLink4Len*armLink4Len}" />
		
		<xacro:macro name="armLink4_geom">
			<geometry>
				<box size="${armLink4Len} ${armLink4Len} ${armLink4Len}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink4_offset">
			<origin rpy = "0 0 0" xyz="0 0 0" />
		</xacro:macro>

		<visual>
			<xacro:armLink4_geom />
			<xacro:armLink4_offset />
			<material name="blue"/>
		</visual>
		<collision>
			<xacro:armLink4_geom />
			<xacro:armLink4_offset />
		</collision>
		<inertial>
			<mass value="${armLink4Mass}" />
			<inertia ixx="${armLink4Len*armLink4Len /6}" ixy="0.0" ixz="0.0" iyy="${armLink4Len*armLink4Len/6}" iyz="0.0" izz="${armLink4Len*armLink4Len /6}" />
		</inertial>
	</link>	
	
	<joint name="armLink3_to_armLink4" type ="continuous">
		<parent link="armLink3square"/>
		<child link="armLink4"/>
		<origin rpy = "0 0 0" xyz="${armLink3squareLen} 0 ${armLink4Len/2}" />
		<axis xyz = "1 0 0" />
	</joint>


	<!--	****************
			****************
			****************

 				Arm Link 5

			****************
			****************
			****************
	-->

	<link name="armLink5">

		<xacro:macro name="armLink5_geom">
			<geometry>
				<cylinder length="${armLink5Len}" radius="${armLink5Rad}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink5_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink5Len/2}" />
		</xacro:macro>

		<xacro:property name="armLink5Rad" value="${cylRad}" />
		<xacro:property name="armLink5Len" value = "${cylLen}" />
		<xacro:property name="armLink5Mass" value = 
				"${AlDensity*3.14*armLink5Len*armLink5Rad*armLink5Rad}" />
		<visual>
			<xacro:armLink5_geom />
			<xacro:armLink5_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink5_geom />
			<xacro:armLink5_offset />
		</collision>
		<inertial>
			<mass value="${armLink5Mass}" />
			<inertia ixx="${armLink5Len*armLink5Len/3+armLink5Rad*armLink5Rad/4}" ixy="0.0" ixz="0.0" iyy="${armLink5Len*armLink5Len/3+armLink5Rad*armLink5Rad/4}" iyz="0.0" izz="${armLink5Rad*armLink5Rad/2}" />
		</inertial>
	</link>

	<joint name="armLink4_to_armLink5" type ="continuous">
		<parent link="armLink4"/>
		<child link="armLink5"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink4Len/2}" />
		<axis xyz = "0 0 1" />
	</joint>

	<link name="armLink5square">
		
		<xacro:property name="armLink5squareLen" value="${armLink5Rad*2.2}" />
		<xacro:property name="armLink5squareMass" value="${AlDensity*armLink5squareLen*armLink5squareLen*armLink5squareLen}" />
		
		<xacro:macro name="armLink5square_geom">
			<geometry>
				<box size="${armLink5squareLen} ${armLink5squareLen} ${armLink5squareLen}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink5square_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink5squareLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:armLink5square_geom />
			<xacro:armLink5square_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink5square_geom />
			<xacro:armLink5square_offset />
		</collision>
		<inertial>
			<mass value="${armLink5squareMass}" />
			<inertia ixx="${armLink5squareLen*armLink5squareLen * 5/12}" ixy="0.0" ixz="0.0" iyy="${armLink5squareLen*armLink5squareLen * 5/12}" iyz="0.0" izz="${armLink5squareLen*armLink5squareLen / 6}" />
		</inertial>
	</link>	

	<joint name="armLink5Fixed" type ="fixed">
		<parent link="armLink5"/>
		<child link="armLink5square"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink5Len}" />
	</joint>

	<!--	****************
			****************
			****************

 				Arm Link 6

			****************
			****************
			****************
	-->


	<link name="armLink6">
		
		<xacro:property name="armLink6Len" value="${armLink5squareLen}" />
		<xacro:property name="armLink6Mass" value="${AlDensity*armLink6Len*armLink6Len*armLink6Len}" />
		
		<xacro:macro name="armLink6_geom">
			<geometry>
				<box size="${armLink6Len} ${armLink6Len} ${armLink6Len}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink6_offset">
			<origin rpy = "0 0 0" xyz="0 0 0" />
		</xacro:macro>

		<visual>
			<xacro:armLink6_geom />
			<xacro:armLink6_offset />
			<material name="blue"/>
		</visual>
		<collision>
			<xacro:armLink6_geom />
			<xacro:armLink6_offset />
		</collision>
		<inertial>
			<mass value="${armLink6Mass}" />
			<inertia ixx="${armLink6Len*armLink6Len /6}" ixy="0.0" ixz="0.0" iyy="${armLink6Len*armLink6Len/6}" iyz="0.0" izz="${armLink6Len*armLink6Len /6}" />
		</inertial>
	</link>	
	
	<joint name="armLink5_to_armLink6" type ="continuous">
		<parent link="armLink5square"/>
		<child link="armLink6"/>
		<origin rpy = "0 0 0" xyz="${-1*armLink5squareLen} 0 ${armLink6Len/2}" />
		<axis xyz = "1 0 0" />
	</joint>

	<!--	****************
			****************
			****************

 				Arm Link 7

			****************
			****************
			****************
	-->


	<link name="armLink7">

		<xacro:macro name="armLink7_geom">
			<geometry>
				<cylinder length="${armLink7Len}" radius="${armLink7Rad}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink7_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink7Len/2}" />
		</xacro:macro>

		<xacro:property name="armLink7Rad" value="${cylRad}" />
		<xacro:property name="armLink7Len" value = "${armLink1Len}" />
		<xacro:property name="armLink7Mass" value = 
				"${AlDensity*3.14*armLink7Len*armLink7Rad*armLink7Rad}" />

		<visual>
			<xacro:armLink7_geom />
			<xacro:armLink7_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink7_geom />
			<xacro:armLink7_offset />
		</collision>
		<inertial>
			<mass value="${armLink7Mass}" />
			<inertia ixx="${armLink7Len*armLink7Len/3+armLink7Rad*armLink7Rad/4}" ixy="0.0" ixz="0.0" iyy="${armLink7Len*armLink7Len/3+armLink7Rad*armLink7Rad/4}" iyz="0.0" izz="${armLink7Rad*armLink7Rad/2}" />
		</inertial>
	</link>

	<joint name="armLink6_to_armLink7" type ="continuous">
		<parent link="armLink6"/>
		<child link="armLink7"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink6Len/2}" />
		<axis xyz = "0 0 1" />
	</joint>

	<link name="armLink7square">
		
		<xacro:property name="armLink7squareLen" value="${armLink7Rad}" />
		<xacro:property name="armLink7squareMass" value="${AlDensity*armLink7squareLen*armLink7squareLen*armLink7squareLen}" />
		
		<xacro:macro name="armLink7square_geom">
			<geometry>
				<box size="${armLink7squareLen} ${armLink7squareLen} ${armLink7squareLen}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="armLink7square_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${armLink7squareLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:armLink7square_geom />
			<xacro:armLink7square_offset />
			<material name="white"/>
		</visual>
		<collision>
			<xacro:armLink7square_geom />
			<xacro:armLink7square_offset />
		</collision>
		<inertial>
			<mass value="${armLink7squareMass}" />
			<inertia ixx="${armLink7squareLen*armLink7squareLen * 5/12}" ixy="0.0" ixz="0.0" iyy="${armLink7squareLen*armLink7squareLen * 5/12}" iyz="0.0" izz="${armLink7squareLen*armLink7squareLen / 6}" />
		</inertial>
	</link>	

	<joint name="armLink7Fixed" type ="fixed">
		<parent link="armLink7"/>
		<child link="armLink7square"/>
		<origin rpy = "0 0 0" xyz="0 0 ${armLink7Len}" />
	</joint>

	<!--	****************
			****************
			****************

 Beginning of the Satellite/Support Section

			****************
			****************
			****************
	-->
				
	<xacro:property name="supArc" value="1" />
	<xacro:property name="supLen" value="1.5" />
	<xacro:property name="supRad" value=".2" />
	<xacro:property name="supMass" value = 
				"${AlDensity*3.14*supLen*supRad*supRad}" />

	<xacro:macro name="sup_geom">
		<geometry>
			<cylinder length="${supLen}" radius="${supRad}"/>
		</geometry>
	</xacro:macro>

	<xacro:macro name="sup_inertia">
		<inertial>
			<mass value="${supMass}" />
			<inertia ixx="${supLen*supLen/3+supRad*supRad/4}" ixy="0.0" ixz="0.0" iyy="${supLen*supLen/3+supRad*supRad/4}" iyz="0.0" izz="${supRad*supRad/2}" />
		</inertial>
	</xacro:macro>
			

	<link name = "support1">
		<xacro:macro name="support1_offset">
			<origin rpy = "0 0 0" xyz = "0 0 ${supLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:sup_geom />
			<xacro:support1_offset />
			<material name="black"/>
		</visual>
		<collision>
			<xacro:sup_geom />
			<xacro:support1_offset />
		</collision>
		<xacro:sup_inertia />
	</link>

	<joint name="base_to_sup1" type ="fixed">
		<parent link="platform_base"/>
		<child link="support1"/>
		<origin rpy = "0 0 0" xyz="${-1*platLen/4} ${-1*supArc} ${platHeight/2}" />
	</joint>

	<link name = "support2">
		<xacro:macro name="support2_offset">
			<origin rpy = "0 0 0" xyz = "0 0 ${supLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:sup_geom />
			<xacro:support1_offset />
			<material name="black"/>
		</visual>
		<collision>
			<xacro:sup_geom />
			<xacro:support1_offset />
		</collision>
		<xacro:sup_inertia />
	</link>

	<joint name="base_to_sup2" type ="fixed">
		<parent link="platform_base"/>
		<child link="support2"/>
		<origin rpy = "0 0 0" xyz="${-1*platLen/4+supArc*1.7/2} ${supArc/2} ${platHeight/2}" />
	</joint>

	<link name = "support3">
		<xacro:macro name="support3_offset">
			<origin rpy = "0 0 0" xyz = "0 0 ${supLen/2}" />
		</xacro:macro>

		<visual>
			<xacro:sup_geom />
			<xacro:support1_offset />
			<material name="black"/>
		</visual>
		<collision>
			<xacro:sup_geom />
			<xacro:support1_offset />
		</collision>
		<xacro:sup_inertia />
	</link>

	<joint name="base_to_sup3" type ="fixed">
		<parent link="platform_base"/>
		<child link="support3"/>
		<origin rpy = "0 0 0" xyz="${-1*platLen/4-supArc*1.7/2} ${supArc/2} ${platHeight/2}" />
	</joint>

	<!--	****************
			****************
			****************

	 			Satellite

			****************
			****************
			****************
	-->

	<link name="satellite">
		
		<xacro:property name="satMass" value="${AlDensity*satLen*satWidth*satHeight}" />
		
		<xacro:macro name="sat_geom">
			<geometry>
				<box size="${satLen} ${satWidth} ${satHeight}"/>
			</geometry>
		</xacro:macro>

		<xacro:macro name="sat_offset">
			<origin rpy = "0 0 0" xyz="0 0 ${satHeight/2}" />
		</xacro:macro>

		<visual>
			<xacro:sat_geom />
			<xacro:sat_offset />
			<material name="black"/>
		</visual>
		<collision>
			<xacro:sat_geom />
			<xacro:sat_offset />
		</collision>
		<inertial>
			<mass value="${satMass}" />
			<inertia ixx="${satHeight*satHeight/3+satWidth*satWidth/12}" ixy="0.0" ixz="0.0" iyy="${satHeight*satHeight/3+satLen*satLen/12}" iyz="0.0" izz="${satLen*satLen/+satWidth*satWidth/12}" />
		</inertial>
	</link>	

	<joint name="sup1_to_satellite" type ="fixed">
		<parent link="support1"/>
		<child link="satellite"/>
		<origin rpy = "0 0 0" xyz="${0} ${supArc} ${supLen}" />
	</joint>


	<!--	****************
			****************
			****************

	 		  Clutter

			****************
			****************
			****************
	-->

	<link name="clutter1">
		<xacro:property name="c1Mass" value="${AlDensity*c1Rad*c1Rad*c1Rad}" />
		<xacro:property name="c1Rad" value=".3" />
		
		<xacro:macro name="c1_geom">
			<geometry>
				<sphere radius="${c1Rad}"/>
			</geometry>
		</xacro:macro>


		<visual>
			<xacro:c1_geom />
			<material name="cyan"/>
		</visual>
		<collision>
			<xacro:c1_geom />
		</collision>
		<inertial>
			<mass value="${c1Mass}" />
			<inertia ixx="${2/5*c1Rad*c1Rad}" ixy="0.0" ixz="0.0" iyy="${2/5*c1Rad*c1Rad}" iyz="0.0" izz="${2/5*c1Rad*c1Rad}" />
		</inertial>
	</link>

	<joint name="platform_to_clutter1" type="fixed">
		<parent link="platform_base"/>
		<child link="clutter1"/>
		<origin rpy = "0 0 0" xyz = "${2} ${2} ${platHeight+2}" />
	</joint>

	<link name="clutter2">
		<xacro:property name="c2Mass" value="${AlDensity*c2Rad*c2Rad*c2Rad}" />
		<xacro:property name="c2Rad" value=".2" />
		
		<xacro:macro name="c2_geom">
			<geometry>
				<sphere radius="${c2Rad}"/>
			</geometry>
		</xacro:macro>


		<visual>
			<xacro:c2_geom />
			<material name="cyan"/>
		</visual>
		<collision>
			<xacro:c2_geom />
		</collision>
		<inertial>
			<mass value="${c2Mass}" />
			<inertia ixx="${2/5*c2Rad*c2Rad}" ixy="0.0" ixz="0.0" iyy="${2/5*c2Rad*c2Rad}" iyz="0.0" izz="${2/5*c2Rad*c2Rad}" />
		</inertial>
	</link>

	<joint name="platform_to_clutter2" type="fixed">
		<parent link="platform_base"/>
		<child link="clutter2"/>
		<origin rpy = "0 0 0" xyz = "${1.5} ${0} ${platHeight+1}" />
	</joint>
</robot>

